// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"news_helper/model"
)

func newNews(db *gorm.DB, opts ...gen.DOOption) news {
	_news := news{}

	_news.newsDo.UseDB(db, opts...)
	_news.newsDo.UseModel(&model.News{})

	tableName := _news.newsDo.TableName()
	_news.ALL = field.NewAsterisk(tableName)
	_news.ID = field.NewUint64(tableName, "id")
	_news.CreatedAt = field.NewUint64(tableName, "created_at")
	_news.UpdatedAt = field.NewUint64(tableName, "updated_at")
	_news.DeletedAt = field.NewUint(tableName, "deleted_at")
	_news.MediaId = field.NewUint(tableName, "media_id")
	_news.Title = field.NewString(tableName, "title")
	_news.Content = field.NewString(tableName, "content")
	_news.Link = field.NewString(tableName, "link")
	_news.Source = field.NewString(tableName, "source")
	_news.Time = field.NewUint64(tableName, "time")

	_news.fillFieldMap()

	return _news
}

type news struct {
	newsDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Uint64
	UpdatedAt field.Uint64
	DeletedAt field.Uint
	MediaId   field.Uint
	Title     field.String
	Content   field.String
	Link      field.String
	Source    field.String
	Time      field.Uint64

	fieldMap map[string]field.Expr
}

func (n news) Table(newTableName string) *news {
	n.newsDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n news) As(alias string) *news {
	n.newsDo.DO = *(n.newsDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *news) updateTableName(table string) *news {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewUint64(table, "id")
	n.CreatedAt = field.NewUint64(table, "created_at")
	n.UpdatedAt = field.NewUint64(table, "updated_at")
	n.DeletedAt = field.NewUint(table, "deleted_at")
	n.MediaId = field.NewUint(table, "media_id")
	n.Title = field.NewString(table, "title")
	n.Content = field.NewString(table, "content")
	n.Link = field.NewString(table, "link")
	n.Source = field.NewString(table, "source")
	n.Time = field.NewUint64(table, "time")

	n.fillFieldMap()

	return n
}

func (n *news) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *news) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 10)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["media_id"] = n.MediaId
	n.fieldMap["title"] = n.Title
	n.fieldMap["content"] = n.Content
	n.fieldMap["link"] = n.Link
	n.fieldMap["source"] = n.Source
	n.fieldMap["time"] = n.Time
}

func (n news) clone(db *gorm.DB) news {
	n.newsDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n news) replaceDB(db *gorm.DB) news {
	n.newsDo.ReplaceDB(db)
	return n
}

type newsDo struct{ gen.DO }

// FirstByID Where("id=@id")
func (n newsDo) FirstByID(id uint64) (result *model.News, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("id=? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Where(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteByID update @@table set deleted_at=NOW() where id=@id
func (n newsDo) DeleteByID(id uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("update news set deleted_at=NOW() where id=? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (n newsDo) Debug() *newsDo {
	return n.withDO(n.DO.Debug())
}

func (n newsDo) WithContext(ctx context.Context) *newsDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n newsDo) ReadDB() *newsDo {
	return n.Clauses(dbresolver.Read)
}

func (n newsDo) WriteDB() *newsDo {
	return n.Clauses(dbresolver.Write)
}

func (n newsDo) Session(config *gorm.Session) *newsDo {
	return n.withDO(n.DO.Session(config))
}

func (n newsDo) Clauses(conds ...clause.Expression) *newsDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n newsDo) Returning(value interface{}, columns ...string) *newsDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n newsDo) Not(conds ...gen.Condition) *newsDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n newsDo) Or(conds ...gen.Condition) *newsDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n newsDo) Select(conds ...field.Expr) *newsDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n newsDo) Where(conds ...gen.Condition) *newsDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n newsDo) Order(conds ...field.Expr) *newsDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n newsDo) Distinct(cols ...field.Expr) *newsDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n newsDo) Omit(cols ...field.Expr) *newsDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n newsDo) Join(table schema.Tabler, on ...field.Expr) *newsDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n newsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *newsDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n newsDo) RightJoin(table schema.Tabler, on ...field.Expr) *newsDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n newsDo) Group(cols ...field.Expr) *newsDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n newsDo) Having(conds ...gen.Condition) *newsDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n newsDo) Limit(limit int) *newsDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n newsDo) Offset(offset int) *newsDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n newsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *newsDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n newsDo) Unscoped() *newsDo {
	return n.withDO(n.DO.Unscoped())
}

func (n newsDo) Create(values ...*model.News) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n newsDo) CreateInBatches(values []*model.News, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n newsDo) Save(values ...*model.News) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n newsDo) First() (*model.News, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.News), nil
	}
}

func (n newsDo) Take() (*model.News, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.News), nil
	}
}

func (n newsDo) Last() (*model.News, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.News), nil
	}
}

func (n newsDo) Find() ([]*model.News, error) {
	result, err := n.DO.Find()
	return result.([]*model.News), err
}

func (n newsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.News, err error) {
	buf := make([]*model.News, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n newsDo) FindInBatches(result *[]*model.News, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n newsDo) Attrs(attrs ...field.AssignExpr) *newsDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n newsDo) Assign(attrs ...field.AssignExpr) *newsDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n newsDo) Joins(fields ...field.RelationField) *newsDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n newsDo) Preload(fields ...field.RelationField) *newsDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n newsDo) FirstOrInit() (*model.News, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.News), nil
	}
}

func (n newsDo) FirstOrCreate() (*model.News, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.News), nil
	}
}

func (n newsDo) FindByPage(offset int, limit int) (result []*model.News, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n newsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n newsDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n newsDo) Delete(models ...*model.News) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *newsDo) withDO(do gen.Dao) *newsDo {
	n.DO = *do.(*gen.DO)
	return n
}
